version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: santhitak/process-image-frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: santhitak/process-image-backend
